development:
  adapter: postgresql
  encoding: unicode
  database: hostel_helper_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: hostel_helper_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: hostel_helper_production
  pool: 5
  password:
